/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface GtStockPrice {
    'stockSymbol': string;
  }
}

declare global {


  interface HTMLGtStockPriceElement extends Components.GtStockPrice, HTMLStencilElement {}
  var HTMLGtStockPriceElement: {
    prototype: HTMLGtStockPriceElement;
    new (): HTMLGtStockPriceElement;
  };
  interface HTMLElementTagNameMap {
    'gt-stock-price': HTMLGtStockPriceElement;
  }
}

declare namespace LocalJSX {
  interface GtStockPrice {
    'stockSymbol'?: string;
  }

  interface IntrinsicElements {
    'gt-stock-price': GtStockPrice;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'gt-stock-price': LocalJSX.GtStockPrice & JSXBase.HTMLAttributes<HTMLGtStockPriceElement>;
    }
  }
}


